### ISSUE TITLE
a problem about speed

### ISSUE THREAD

**Issue by rainbow520lxr** [Po-Ting-lin/RandomizedHoughEllipseDetector#5]
This algorithm will be very slow without mask ， because max_iter is too large

**Comment by Po-Ting-lin** [comment]
There are plenty of factors can affect the elapsed time. If canny edge detector get too many useless edge pixels(too sensitive), it will waste the effort to deal with those edge pixels. Therefore, it is critical to adjust the parameters of canny. Moreover, a proper mask also can reduce the useless edge pixels. You can decrease the number of iteration of this algorithm, but the accuracy will decrease due to lack of sampling the target edge pixels. Try to adjust these parameters and analyze it~
